# Generated by Django 6.0.4 on 2026-04-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
