# Generated by Django 6.0.4 on 2026-06-16 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_client_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='pieces',
            field=models.IntegerField(blank=True, help_text='Nombre de pièces', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bien',
            name='surface',
            field=models.IntegerField(blank=True, help_text='Surface en m²', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
