# Generated by Django 6.0.4 on 2026-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_alter_bien_pieces_alter_bien_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='type_transaction',
            field=models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], default='vente', max_length=10),
        ),
    ]
