# Generated by Django 5.2.15 on 2026-06-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_bien_type_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='heure_visite_souhaitee',
            field=models.TimeField(blank=True, help_text='Heure souhaitée (entre 8h et 18h)', null=True),
        ),
    ]
