# Generated by Django 5.2.15 on 2026-06-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_demande_heure_visite_souhaitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='premium_jusqu_au',
            field=models.DateField(blank=True, help_text="Date de fin de l'abonnement premium (mis en avant sur le site). Laisser vide si l'agence n'est pas abonnée.", null=True, verbose_name="Premium jusqu'au"),
        ),
    ]
